/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System;
using System.Collections.Generic;
using Twilio.Base;
using Twilio.Converters;

namespace Twilio.Rest.Supersim.V1.Sim
{

    /// <summary>
    /// PLEASE NOTE that this class contains beta products that are subject to change. Use them with caution.
    ///
    /// Retrieve a list of IP Addresses for the given Super SIM.
    /// </summary>
    public class ReadSimIpAddressOptions : ReadOptions<SimIpAddressResource>
    {
        /// <summary>
        /// The SID of the Super SIM to list IP Addresses for.
        /// </summary>
        public string PathSimSid { get; }

        /// <summary>
        /// Construct a new ReadSimIpAddressOptions
        /// </summary>
        /// <param name="pathSimSid"> The SID of the Super SIM to list IP Addresses for. </param>
        public ReadSimIpAddressOptions(string pathSimSid)
        {
            PathSimSid = pathSimSid;
        }

        /// <summary>
        /// Generate the necessary parameters
        /// </summary>
        public override List<KeyValuePair<string, string>> GetParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            if (PageSize != null)
            {
                p.Add(new KeyValuePair<string, string>("PageSize", PageSize.ToString()));
            }

            return p;
        }
    }

}