FROM python:3.7.5-stretch
ENV HOME /root

##### C#
# Notes: doxygen is for generating the C# docs.
ENV FrameworkPathOverride /usr/lib/mono/4.5/

RUN apt-get update && apt-get -y install apt-transport-https

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
    && echo "deb https://download.mono-project.com/repo/debian stable-stretch main" > /etc/apt/sources.list.d/mono-official-stable.list \
    && apt-get update \
    && apt-get install -y mono-devel

RUN wget -O packages-microsoft-prod.deb https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y mono-devel libunwind8 doxygen dotnet-sdk-3.1

RUN mkdir /twilio
WORKDIR /twilio

COPY src ./src
COPY test ./test
COPY Twilio.sln .

RUN dotnet restore
RUN dotnet build -c Release