/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System;
using System.Collections.Generic;
using Twilio.Base;
using Twilio.Converters;

namespace Twilio.Rest.Accounts.V1
{

    /// <summary>
    /// Promote the secondary Auth Token to primary. After promoting the new token, all requests to Twilio using your old
    /// primary Auth Token will result in an error.
    /// </summary>
    public class UpdateAuthTokenPromotionOptions : IOptions<AuthTokenPromotionResource>
    {
        /// <summary>
        /// Generate the necessary parameters
        /// </summary>
        public List<KeyValuePair<string, string>> GetParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            return p;
        }
    }

}