/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio Conversational Intelligence API
 * The Conversational Intelligence API includes resources to create and manage intelligence configurations, define and run language operators, and retrieve processed conversations and operator results.  * Use the Configurations resource to create and manage intelligence configurations and define rules that control how and when language operators analyze and transform conversations.  * Use the Operators resource to create custom language operators or retrieve Twilio-author and custom operators. * Use the Conversations resource to retrieve conversations processed with an intelligence configuration, and the OperatorResults resource to retrieve language operator results for those conversations. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Twilio.Base;
using Twilio.Clients;
using Twilio.Constant;
using Twilio.Converters;
using Twilio.Exceptions;
using Twilio.Http;


namespace Twilio.Rest.Intelligence.V3
{
            public class OperatorResultFetchResource : Resource
{
        ///<summary> The ID of the Account that created the Language Operator. </summary> 
        [JsonProperty("accountId")]
            public string AccountId { get; private set; }

        ///<summary> The `id` of the Conversation attached to the Operator Result. </summary> 
        [JsonProperty("conversationId")]
            public string ConversationId { get; private set; }

        ///<summary> Timestamp for when the Operator Result was created. </summary> 
        [JsonProperty("dateCreated")]
            public DateTime? DateCreated { get; private set; }

        ///<summary> The executionDetails </summary> 
        [JsonProperty("executionDetails")]
            public OperatorResultResource.ExecutionDetails _ExecutionDetails { get; private set; }

        ///<summary> A unique identifier for the Operator Result. Assigned by Twilio (TTID). </summary> 
        [JsonProperty("id")]
            public string Id { get; private set; }

        ///<summary> The intelligenceConfiguration </summary> 
        [JsonProperty("intelligenceConfiguration")]
            public OperatorResultResource.IntelligenceConfigurationReference IntelligenceConfiguration { get; private set; }

        ///<summary> The metadata </summary> 
        [JsonProperty("metadata")]
            public OperatorResultResource.OperatorResultsResponseBaseMetadata Metadata { get; private set; }

        ///<summary> The operator </summary> 
        [JsonProperty("operator")]
            public OperatorResultResource.OperatorReference Operator { get; private set; }

        ///<summary> The output format set on the Operator that generated this result. Determines the structure of the `result` object. </summary> 
        [JsonProperty("outputFormat")]
            public string OutputFormat { get; private set; }

        ///<summary> The `id`s of objects related to this Operator Result. </summary> 
        [JsonProperty("referenceIds")]
            public List<string> ReferenceIds { get; private set; }

        ///<summary> The result </summary> 
        [JsonProperty("result")]
            public OperatorResultResource.TextResultResult Result { get; private set; }


    public static OperatorResultFetchResource FromJson(string json) {
        try {
            return JsonConvert.DeserializeObject<OperatorResultFetchResource>(json);
        }
        catch (JsonException e) {
            throw new ApiException(e.Message, e);
        }
    }
    public static string ToJson(object model) {
        try {
            return JsonConvert.SerializeObject(model);
        }
        catch (JsonException e) {
            throw new ApiException(e.Message, e);
        }
    }
}
        public class OperatorResultReadResource : Resource
{
            ///<summary> The ID of the Account that created the Language Operator. </summary> 
            [JsonProperty("accountId")]
                public string AccountId { get; private set; }

            ///<summary> The `id` of the Conversation attached to the Operator Result. </summary> 
            [JsonProperty("conversationId")]
                public string ConversationId { get; private set; }

            ///<summary> Timestamp for when the Operator Result was created. </summary> 
            [JsonProperty("dateCreated")]
                public DateTime? DateCreated { get; private set; }

            ///<summary> The executionDetails </summary> 
            [JsonProperty("executionDetails")]
                public OperatorResultResource.ExecutionDetails _ExecutionDetails { get; private set; }

            ///<summary> A unique identifier for the Operator Result. Assigned by Twilio (TTID). </summary> 
            [JsonProperty("id")]
                public string Id { get; private set; }

            ///<summary> The intelligenceConfiguration </summary> 
            [JsonProperty("intelligenceConfiguration")]
                public OperatorResultResource.IntelligenceConfigurationReference IntelligenceConfiguration { get; private set; }

            ///<summary> The metadata </summary> 
            [JsonProperty("metadata")]
                public OperatorResultResource.OperatorResultsResponseBaseMetadata Metadata { get; private set; }

            ///<summary> The operator </summary> 
            [JsonProperty("operator")]
                public OperatorResultResource.OperatorReference Operator { get; private set; }

            ///<summary> The output format set on the Operator that generated this result. Determines the structure of the `result` object. </summary> 
            [JsonProperty("outputFormat")]
                public string OutputFormat { get; private set; }

            ///<summary> The `id`s of objects related to this Operator Result. </summary> 
            [JsonProperty("referenceIds")]
                public List<string> ReferenceIds { get; private set; }

            ///<summary> The result </summary> 
            [JsonProperty("result")]
                public OperatorResultResource.TextResultResult Result { get; private set; }


    public static OperatorResultReadResource FromJson(string json) {
        try {
            return JsonConvert.DeserializeObject<OperatorResultReadResource>(json);
        }
        catch (JsonException e) {
            throw new ApiException(e.Message, e);
        }
    }
    public static string ToJson(object model) {
        try {
            return JsonConvert.SerializeObject(model);
        }
        catch (JsonException e) {
            throw new ApiException(e.Message, e);
        }
    }
}

    public class OperatorResultResource : Resource
    {
    
        public class ExecutionDetailsTrigger
        {
            [JsonProperty("on", NullValueHandling = NullValueHandling.Ignore)]
            public string On {get; private set;}
            [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore)]
            public DateTime? Timestamp {get; private set;}
            public ExecutionDetailsTrigger() { }
            public class Builder
            {
                private ExecutionDetailsTrigger _executionDetailsTrigger = new ExecutionDetailsTrigger();
                public Builder()
                {
                }
                public Builder WithOn(string on)
                {
                    _executionDetailsTrigger.On= on;
                    return this;
                }
                public Builder WithTimestamp(DateTime? timestamp)
                {
                    _executionDetailsTrigger.Timestamp= timestamp;
                    return this;
                }
                public ExecutionDetailsTrigger Build()
                {
                    return _executionDetailsTrigger;
                }
            }
        }
        public class ExecutionDetailsCommunications
        {
            [JsonProperty("first", NullValueHandling = NullValueHandling.Ignore)]
            public string First {get; private set;}
            [JsonProperty("last", NullValueHandling = NullValueHandling.Ignore)]
            public string Last {get; private set;}
            public ExecutionDetailsCommunications() { }
            public class Builder
            {
                private ExecutionDetailsCommunications _executionDetailsCommunications = new ExecutionDetailsCommunications();
                public Builder()
                {
                }
                public Builder WithFirst(string first)
                {
                    _executionDetailsCommunications.First= first;
                    return this;
                }
                public Builder WithLast(string last)
                {
                    _executionDetailsCommunications.Last= last;
                    return this;
                }
                public ExecutionDetailsCommunications Build()
                {
                    return _executionDetailsCommunications;
                }
            }
        }
        public class ExecutionDetailsParticipants
        {
            [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
            public string Id {get; private set;}
            [JsonProperty("profileId", NullValueHandling = NullValueHandling.Ignore)]
            public string ProfileId {get; private set;}
            [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
            public string Type {get; private set;}
            public ExecutionDetailsParticipants() { }
            public class Builder
            {
                private ExecutionDetailsParticipants _executionDetailsParticipants = new ExecutionDetailsParticipants();
                public Builder()
                {
                }
                public Builder WithId(string id)
                {
                    _executionDetailsParticipants.Id= id;
                    return this;
                }
                public Builder WithProfileId(string profileId)
                {
                    _executionDetailsParticipants.ProfileId= profileId;
                    return this;
                }
                public Builder WithType(string type)
                {
                    _executionDetailsParticipants.Type= type;
                    return this;
                }
                public ExecutionDetailsParticipants Build()
                {
                    return _executionDetailsParticipants;
                }
            }
        }
        public class ResolvedContextMemory
        {
            [JsonProperty("profileId", NullValueHandling = NullValueHandling.Ignore)]
            public string ProfileId {get; private set;}
            [JsonProperty("memoryStoreId", NullValueHandling = NullValueHandling.Ignore)]
            public string MemoryStoreId {get; private set;}
            public ResolvedContextMemory() { }
            public class Builder
            {
                private ResolvedContextMemory _resolvedContextMemory = new ResolvedContextMemory();
                public Builder()
                {
                }
                public Builder WithProfileId(string profileId)
                {
                    _resolvedContextMemory.ProfileId= profileId;
                    return this;
                }
                public Builder WithMemoryStoreId(string memoryStoreId)
                {
                    _resolvedContextMemory.MemoryStoreId= memoryStoreId;
                    return this;
                }
                public ResolvedContextMemory Build()
                {
                    return _resolvedContextMemory;
                }
            }
        }
        public class ResolvedContextKnowledgeSources
        {
            [JsonProperty("baseId", NullValueHandling = NullValueHandling.Ignore)]
            public string BaseId {get; private set;}
            [JsonProperty("sourceId", NullValueHandling = NullValueHandling.Ignore)]
            public string SourceId {get; private set;}
            public ResolvedContextKnowledgeSources() { }
            public class Builder
            {
                private ResolvedContextKnowledgeSources _resolvedContextKnowledgeSources = new ResolvedContextKnowledgeSources();
                public Builder()
                {
                }
                public Builder WithBaseId(string baseId)
                {
                    _resolvedContextKnowledgeSources.BaseId= baseId;
                    return this;
                }
                public Builder WithSourceId(string sourceId)
                {
                    _resolvedContextKnowledgeSources.SourceId= sourceId;
                    return this;
                }
                public ResolvedContextKnowledgeSources Build()
                {
                    return _resolvedContextKnowledgeSources;
                }
            }
        }
        public class ResolvedContextKnowledge
        {
            [JsonProperty("sources", NullValueHandling = NullValueHandling.Ignore)]
            public List<OperatorResultResource.ResolvedContextKnowledgeSources> Sources {get; private set;}
            public ResolvedContextKnowledge() { }
            public class Builder
            {
                private ResolvedContextKnowledge _resolvedContextKnowledge = new ResolvedContextKnowledge();
                public Builder()
                {
                }
                public Builder WithSources(List<OperatorResultResource.ResolvedContextKnowledgeSources> sources)
                {
                    _resolvedContextKnowledge.Sources= sources;
                    return this;
                }
                public ResolvedContextKnowledge Build()
                {
                    return _resolvedContextKnowledge;
                }
            }
        }
        public class ResolvedContext
        {
            [JsonProperty("memory", NullValueHandling = NullValueHandling.Ignore)]
            public OperatorResultResource.ResolvedContextMemory Memory {get; private set;}
            [JsonProperty("knowledge", NullValueHandling = NullValueHandling.Ignore)]
            public OperatorResultResource.ResolvedContextKnowledge Knowledge {get; private set;}
            public ResolvedContext() { }
            public class Builder
            {
                private ResolvedContext _resolvedContext = new ResolvedContext();
                public Builder()
                {
                }
                public Builder WithMemory(OperatorResultResource.ResolvedContextMemory memory)
                {
                    _resolvedContext.Memory= memory;
                    return this;
                }
                public Builder WithKnowledge(OperatorResultResource.ResolvedContextKnowledge knowledge)
                {
                    _resolvedContext.Knowledge= knowledge;
                    return this;
                }
                public ResolvedContext Build()
                {
                    return _resolvedContext;
                }
            }
        }
        public class ExecutionDetails
        {
            [JsonProperty("trigger", NullValueHandling = NullValueHandling.Ignore)]
            public OperatorResultResource.ExecutionDetailsTrigger Trigger {get; private set;}
            [JsonProperty("communications", NullValueHandling = NullValueHandling.Ignore)]
            public OperatorResultResource.ExecutionDetailsCommunications Communications {get; private set;}
            [JsonProperty("channels", NullValueHandling = NullValueHandling.Ignore)]
            public List<string> Channels {get; private set;}
            [JsonProperty("participants", NullValueHandling = NullValueHandling.Ignore)]
            public List<OperatorResultResource.ExecutionDetailsParticipants> Participants {get; private set;}
            [JsonProperty("resolvedContext", NullValueHandling = NullValueHandling.Ignore)]
            public OperatorResultResource.ResolvedContext ResolvedContext {get; private set;}
            public ExecutionDetails() { }
            public class Builder
            {
                private ExecutionDetails _executionDetails = new ExecutionDetails();
                public Builder()
                {
                }
                public Builder WithTrigger(OperatorResultResource.ExecutionDetailsTrigger trigger)
                {
                    _executionDetails.Trigger= trigger;
                    return this;
                }
                public Builder WithCommunications(OperatorResultResource.ExecutionDetailsCommunications communications)
                {
                    _executionDetails.Communications= communications;
                    return this;
                }
                public Builder WithChannels(List<string> channels)
                {
                    _executionDetails.Channels= channels;
                    return this;
                }
                public Builder WithParticipants(List<OperatorResultResource.ExecutionDetailsParticipants> participants)
                {
                    _executionDetails.Participants= participants;
                    return this;
                }
                public Builder WithResolvedContext(OperatorResultResource.ResolvedContext resolvedContext)
                {
                    _executionDetails.ResolvedContext= resolvedContext;
                    return this;
                }
                public ExecutionDetails Build()
                {
                    return _executionDetails;
                }
            }
        }
        public class IntelligenceConfigurationReference
        {
            [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
            public string Id {get; private set;}
            [JsonProperty("ruleId", NullValueHandling = NullValueHandling.Ignore)]
            public string RuleId {get; private set;}
            [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
            public int? Version {get; private set;}
            public IntelligenceConfigurationReference() { }
            public class Builder
            {
                private IntelligenceConfigurationReference _intelligenceConfigurationReference = new IntelligenceConfigurationReference();
                public Builder()
                {
                }
                public Builder WithId(string id)
                {
                    _intelligenceConfigurationReference.Id= id;
                    return this;
                }
                public Builder WithRuleId(string ruleId)
                {
                    _intelligenceConfigurationReference.RuleId= ruleId;
                    return this;
                }
                public Builder WithVersion(int? version)
                {
                    _intelligenceConfigurationReference.Version= version;
                    return this;
                }
                public IntelligenceConfigurationReference Build()
                {
                    return _intelligenceConfigurationReference;
                }
            }
        }
        public class SystemMetaData
        {
            [JsonProperty("latencyMs", NullValueHandling = NullValueHandling.Ignore)]
            public int? LatencyMs {get; private set;}
            [JsonProperty("inputCharacters", NullValueHandling = NullValueHandling.Ignore)]
            public int? InputCharacters {get; private set;}
            [JsonProperty("outputCharacters", NullValueHandling = NullValueHandling.Ignore)]
            public int? OutputCharacters {get; private set;}
            [JsonProperty("inputTruncated", NullValueHandling = NullValueHandling.Ignore)]
            public bool? InputTruncated {get; private set;}
            [JsonProperty("resolvedModel", NullValueHandling = NullValueHandling.Ignore)]
            public string ResolvedModel {get; private set;}
            public SystemMetaData() { }
            public class Builder
            {
                private SystemMetaData _systemMetaData = new SystemMetaData();
                public Builder()
                {
                }
                public Builder WithLatencyMs(int? latencyMs)
                {
                    _systemMetaData.LatencyMs= latencyMs;
                    return this;
                }
                public Builder WithInputCharacters(int? inputCharacters)
                {
                    _systemMetaData.InputCharacters= inputCharacters;
                    return this;
                }
                public Builder WithOutputCharacters(int? outputCharacters)
                {
                    _systemMetaData.OutputCharacters= outputCharacters;
                    return this;
                }
                public Builder WithInputTruncated(bool? inputTruncated)
                {
                    _systemMetaData.InputTruncated= inputTruncated;
                    return this;
                }
                public Builder WithResolvedModel(string resolvedModel)
                {
                    _systemMetaData.ResolvedModel= resolvedModel;
                    return this;
                }
                public SystemMetaData Build()
                {
                    return _systemMetaData;
                }
            }
        }
        public class OperatorResultsResponseBaseMetadata
        {
            [JsonProperty("system", NullValueHandling = NullValueHandling.Ignore)]
            public OperatorResultResource.SystemMetaData System {get; private set;}
            public OperatorResultsResponseBaseMetadata() { }
            public class Builder
            {
                private OperatorResultsResponseBaseMetadata _operatorResultsResponseBaseMetadata = new OperatorResultsResponseBaseMetadata();
                public Builder()
                {
                }
                public Builder WithSystem(OperatorResultResource.SystemMetaData varSystem)
                {
                    _operatorResultsResponseBaseMetadata.System= varSystem;
                    return this;
                }
                public OperatorResultsResponseBaseMetadata Build()
                {
                    return _operatorResultsResponseBaseMetadata;
                }
            }
        }
        public class OperatorReference
        {
            [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
            public string Id {get; private set;}
            [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
            public int? Version {get; private set;}
            [JsonProperty("parameters", NullValueHandling = NullValueHandling.Ignore)]
            public Dictionary<string, object> Parameters {get; private set;}
            public OperatorReference() { }
            public class Builder
            {
                private OperatorReference _operatorReference = new OperatorReference();
                public Builder()
                {
                }
                public Builder WithId(string id)
                {
                    _operatorReference.Id= id;
                    return this;
                }
                public Builder WithVersion(int? version)
                {
                    _operatorReference.Version= version;
                    return this;
                }
                public Builder WithParameters(Dictionary<string, object> parameters)
                {
                    _operatorReference.Parameters= parameters;
                    return this;
                }
                public OperatorReference Build()
                {
                    return _operatorReference;
                }
            }
        }
        public class TextResultResult
        {
            [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
            public string Text {get; private set;}
            public TextResultResult() { }
            public class Builder
            {
                private TextResultResult _textResultResult = new TextResultResult();
                public Builder()
                {
                }
                public Builder WithText(string text)
                {
                    _textResultResult.Text= text;
                    return this;
                }
                public TextResultResult Build()
                {
                    return _textResultResult;
                }
            }
        }

    

            
        /// <summary> delete </summary>
        /// <param name="options"> Delete OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        private static Request BuildDeleteRequest(DeleteOperatorResultOptions options, ITwilioRestClient client)
        {
            
            string path = "/v3/OperatorResults/{operatorResultId}";

            string PathOperatorResultId = options.PathOperatorResultId;
            path = path.Replace("{"+"operatorResultId"+"}", PathOperatorResultId);

            return new Request(
                HttpMethod.Delete,
                Rest.Domain.Intelligence,
                path,
                queryParams: options.GetParams(),
                headerParams: null
            );
        }

        /// <summary> delete </summary>
        /// <param name="options"> Delete OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static bool Delete(DeleteOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildDeleteRequest(options, client));
        
          return (int)response.StatusCode >= 200 && (int)response.StatusCode < 400; 
           
        }

        #if !NET35
        /// <summary> delete </summary>
        /// <param name="options"> Delete OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<bool> DeleteAsync(DeleteOperatorResultOptions options,
                                                                        ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildDeleteRequest(options, client));
        
          return (int)response.StatusCode >= 200 && (int)response.StatusCode < 400; 
        }
        #endif

        /// <summary> delete </summary>
        /// <param name="pathOperatorResultId"> Operator Result id (TTID) </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static bool Delete(string pathOperatorResultId, ITwilioRestClient client = null)
        {
            var options = new DeleteOperatorResultOptions(pathOperatorResultId)     ;
            return Delete(options, client);
        }

        #if !NET35
        /// <summary> delete </summary>
        /// <param name="pathOperatorResultId"> Operator Result id (TTID) </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<bool> DeleteAsync(string pathOperatorResultId, ITwilioRestClient client = null)
        {
            var options = new DeleteOperatorResultOptions(pathOperatorResultId) ;
            return await DeleteAsync(options, client);
        }
        #endif

        public static TwilioResponse<bool> DeleteWithHeaders(DeleteOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildDeleteRequest(options, client));
        
          var success = (int)response.StatusCode >= 200 && (int)response.StatusCode < 400; 
            return new TwilioResponse<bool>(success, response.Headers, response.StatusCode);
        }

        #if !NET35
        public static async System.Threading.Tasks.Task<TwilioResponse<bool>> DeleteWithHeadersAsync(DeleteOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildDeleteRequest(options, client));
        
          var success = (int)response.StatusCode >= 200 && (int)response.StatusCode < 400; 
            return new TwilioResponse<bool>(success, response.Headers, response.StatusCode);
        }
        #endif

        public static TwilioResponse<bool> DeleteWithHeaders(string pathOperatorResultId, ITwilioRestClient client = null)
        {
            var options = new DeleteOperatorResultOptions(pathOperatorResultId)     ;
            return DeleteWithHeaders(options, client);
        }

        #if !NET35
        public static async System.Threading.Tasks.Task<TwilioResponse<bool>> DeleteWithHeadersAsync(string pathOperatorResultId, ITwilioRestClient client = null)
        {
            var options = new DeleteOperatorResultOptions(pathOperatorResultId) ;
            return await DeleteWithHeadersAsync(options, client);
        }
        #endif
            
        private static Request BuildFetchRequest(FetchOperatorResultOptions options, ITwilioRestClient client)
        {
            
            string path = "/v3/OperatorResults/{operatorResultId}";

            string PathOperatorResultId = options.PathOperatorResultId;
            path = path.Replace("{"+"operatorResultId"+"}", PathOperatorResultId);

            return new Request(
                HttpMethod.Get,
                Rest.Domain.Intelligence,
                path,
                queryParams: options.GetParams(),
                headerParams: null
            );
        }

        /// <summary> fetch </summary>
        /// <param name="options"> Fetch OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static OperatorResultFetchResource Fetch(FetchOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildFetchRequest(options, client));
            return OperatorResultFetchResource.FromJson(response.Content);
        }

        #if !NET35
        /// <summary> fetch </summary>
        /// <param name="options"> Fetch OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<OperatorResultFetchResource> FetchAsync(FetchOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildFetchRequest(options, client));
            return OperatorResultFetchResource.FromJson(response.Content);
        }
        #endif
        /// <summary> fetch </summary>
        /// <param name="pathOperatorResultId"> Operator Result id (TTID) </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static OperatorResultFetchResource Fetch(
                                         string pathOperatorResultId, 
                                        ITwilioRestClient client = null)
        {
            var options = new FetchOperatorResultOptions(pathOperatorResultId){  };
            return Fetch(options, client);
        }

        #if !NET35
        /// <summary> fetch </summary>
        /// <param name="pathOperatorResultId"> Operator Result id (TTID) </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<OperatorResultFetchResource> FetchAsync(string pathOperatorResultId, ITwilioRestClient client = null)
        {
            var options = new FetchOperatorResultOptions(pathOperatorResultId){  };
            return await FetchAsync(options, client);
        }
        #endif
            
        public static TwilioResponse<OperatorResultFetchResource> FetchWithHeaders(FetchOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildFetchRequest(options, client));
            var resource = OperatorResultFetchResource.FromJson(response.Content);
            return new TwilioResponse<OperatorResultFetchResource>(resource, response.Headers, response.StatusCode);
        }
        #if !NET35
        public static async System.Threading.Tasks.Task<TwilioResponse<OperatorResultFetchResource>> FetchWithHeadersAsync(FetchOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildFetchRequest(options, client));
            var resource = OperatorResultFetchResource.FromJson(response.Content);
            return new TwilioResponse<OperatorResultFetchResource>(resource, response.Headers, response.StatusCode);
        }
        #endif
        
        public static TwilioResponse<OperatorResultFetchResource> FetchWithHeaders(
                    string pathOperatorResultId, 
                ITwilioRestClient client = null)
        {
            var options = new FetchOperatorResultOptions(pathOperatorResultId){  };
            return FetchWithHeaders(options, client);
        }
        
        #if !NET35
        public static async System.Threading.Tasks.Task<TwilioResponse<OperatorResultFetchResource>> FetchWithHeadersAsync(string pathOperatorResultId, ITwilioRestClient client = null)
        {
            var options = new FetchOperatorResultOptions(pathOperatorResultId){  };
            return await FetchWithHeadersAsync(options, client);
        }
        #endif
            
        private static Request BuildReadRequest(ReadOperatorResultOptions options, ITwilioRestClient client)
        {
            
            string path = "/v3/OperatorResults";


            return new Request(
                HttpMethod.Get,
                Rest.Domain.Intelligence,
                path,
                queryParams: options.GetParams(),
                headerParams: null
            );
        }
        /// <summary> read </summary>
        /// <param name="options"> Read OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static ResourceSet<OperatorResultReadResource> Read(ReadOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildReadRequest(options, client));
            var page = Page<OperatorResultReadResource>.FromJson("items", response.Content);
            return new ResourceSet<OperatorResultReadResource>(page, options, client);
        }

        #if !NET35
        /// <summary> read </summary>
        /// <param name="options"> Read OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<ResourceSet<OperatorResultReadResource>> ReadAsync(ReadOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildReadRequest(options, client));

            var page = Page<OperatorResultReadResource>.FromJson("items", response.Content);
            return new ResourceSet<OperatorResultReadResource>(page, options, client);
        }
        #endif
        /// <summary> read </summary>
        /// <param name="conversationId"> Filter Operator Results by attached Conversation `id`. </param>
        /// <param name="intelligenceConfigurationId"> Filter Operator Results by Intelligence Configuration `id` used to generate them. </param>
        /// <param name="operatorId"> Filter Operator Results by Language Operator `id`. </param>
        /// <param name="pageSize"> The maximum number of resources to return </param>
        /// <param name="limit"> Record limit </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static ResourceSet<OperatorResultReadResource> Read(
                                                     string conversationId = null,
                                                     string intelligenceConfigurationId = null,
                                                     string operatorId = null,
                                                     int? pageSize = null,
                                                     long? limit = null,
                                                    ITwilioRestClient client = null)
        {
            var options = new ReadOperatorResultOptions(){ ConversationId = conversationId, IntelligenceConfigurationId = intelligenceConfigurationId, OperatorId = operatorId, PageSize = pageSize, Limit = limit};
            return Read(options, client);
        }

        #if !NET35
        /// <summary> read </summary>
        /// <param name="conversationId"> Filter Operator Results by attached Conversation `id`. </param>
        /// <param name="intelligenceConfigurationId"> Filter Operator Results by Intelligence Configuration `id` used to generate them. </param>
        /// <param name="operatorId"> Filter Operator Results by Language Operator `id`. </param>
        /// <param name="pageSize"> The maximum number of resources to return </param>
        /// <param name="limit"> Record limit </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<ResourceSet<OperatorResultReadResource>> ReadAsync(
                                                                                             string conversationId = null,
                                                                                             string intelligenceConfigurationId = null,
                                                                                             string operatorId = null,
                                                                                             int? pageSize = null,
                                                                                             long? limit = null,
                                                                                            ITwilioRestClient client = null)
        {
            var options = new ReadOperatorResultOptions(){ ConversationId = conversationId, IntelligenceConfigurationId = intelligenceConfigurationId, OperatorId = operatorId, PageSize = pageSize, Limit = limit};
            return await ReadAsync(options, client);
        }
        #endif

        public static ResourceSetResponse<OperatorResultReadResource> ReadWithHeaders(ReadOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildReadRequest(options, client));
            var page = Page<OperatorResultReadResource>.FromJson("items", response.Content);
            var records = new ResourceSet<OperatorResultReadResource>(page, options, client);
            return new ResourceSetResponse<OperatorResultReadResource>(records, response.Headers, response.StatusCode);
        }

        public static ResourceSetResponse<OperatorResultReadResource> ReadWithHeaders(
            string conversationId = null,
            string intelligenceConfigurationId = null,
            string operatorId = null,
            int? pageSize = null,
            long? limit = null,
            ITwilioRestClient client = null)
        {
            var options = new ReadOperatorResultOptions(){ ConversationId = conversationId, IntelligenceConfigurationId = intelligenceConfigurationId, OperatorId = operatorId, PageSize = pageSize, Limit = limit};
            return ReadWithHeaders(options, client);
        }

        #if !NET35
        public static async System.Threading.Tasks.Task<ResourceSetResponse<OperatorResultReadResource>> ReadWithHeadersAsync(ReadOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildReadRequest(options, client));

            var page = Page<OperatorResultReadResource>.FromJson("items", response.Content);
            var records = new ResourceSet<OperatorResultReadResource>(page, options, client);
            return new ResourceSetResponse<OperatorResultReadResource>(records, response.Headers, response.StatusCode);
        }
        #endif
        
        
        /// <summary> Fetch the target page of records </summary>
        /// <param name="targetUrl"> API-generated URL for the requested results page </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> The target page of records </returns>
        public static Page<OperatorResultResource> GetPage(string targetUrl, ITwilioRestClient client)
        {
            client = client ?? TwilioClient.GetRestClient();

            var request = new Request(
                HttpMethod.Get,
                targetUrl
            );

            var response = client.Request(request);
            return Page<OperatorResultResource>.FromJson("items", response.Content);
        }

        /// <summary> Fetch the next page of records </summary>
        /// <param name="page"> current page of records </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> The next page of records </returns>
        public static Page<OperatorResultResource> NextPage(Page<OperatorResultResource> page, ITwilioRestClient client)
        {
            var request = new Request(
                HttpMethod.Get,
                page.GetNextPageUrl(Rest.Domain.Api)
            );

            var response = client.Request(request);
            return Page<OperatorResultResource>.FromJson("items", response.Content);
        }

        /// <summary> Fetch the previous page of records </summary>
        /// <param name="page"> current page of records </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> The previous page of records </returns>
        public static Page<OperatorResultResource> PreviousPage(Page<OperatorResultResource> page, ITwilioRestClient client)
        {
            var request = new Request(
                HttpMethod.Get,
                page.GetPreviousPageUrl(Rest.Domain.Api)
            );

            var response = client.Request(request);
            return Page<OperatorResultResource>.FromJson("items", response.Content);
        }

        /// <summary>
    /// Converts an object into a json string
    /// </summary>
    /// <param name="model"> C# model </param>
    /// <returns> JSON string </returns>
    public static string ToJson(object model)
    {
        try
        {
            return JsonConvert.SerializeObject(model);
        }
        catch (JsonException e)
        {
            throw new ApiException(e.Message, e);
        }
    }
    }
}
