/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System;
using System.Collections.Generic;
using Twilio.Base;
using Twilio.Converters;

namespace Twilio.Rest.Insights.V1
{

    /// <summary>
    /// ReadCallSummariesOptions
    /// </summary>
    public class ReadCallSummariesOptions : ReadOptions<CallSummariesResource>
    {
        /// <summary>
        /// The from
        /// </summary>
        public string From { get; set; }
        /// <summary>
        /// The to
        /// </summary>
        public string To { get; set; }
        /// <summary>
        /// The from_carrier
        /// </summary>
        public string FromCarrier { get; set; }
        /// <summary>
        /// The to_carrier
        /// </summary>
        public string ToCarrier { get; set; }
        /// <summary>
        /// The from_country_code
        /// </summary>
        public string FromCountryCode { get; set; }
        /// <summary>
        /// The to_country_code
        /// </summary>
        public string ToCountryCode { get; set; }
        /// <summary>
        /// The branded
        /// </summary>
        public bool? Branded { get; set; }
        /// <summary>
        /// The verified_caller
        /// </summary>
        public bool? VerifiedCaller { get; set; }
        /// <summary>
        /// The has_tag
        /// </summary>
        public bool? HasTag { get; set; }
        /// <summary>
        /// The start_time
        /// </summary>
        public string StartTime { get; set; }
        /// <summary>
        /// The end_time
        /// </summary>
        public string EndTime { get; set; }
        /// <summary>
        /// The call_type
        /// </summary>
        public string CallType { get; set; }
        /// <summary>
        /// The call_state
        /// </summary>
        public string CallState { get; set; }
        /// <summary>
        /// The direction
        /// </summary>
        public string Direction { get; set; }
        /// <summary>
        /// The processing_state
        /// </summary>
        public CallSummariesResource.ProcessingStateRequestEnum ProcessingState { get; set; }
        /// <summary>
        /// The sort_by
        /// </summary>
        public CallSummariesResource.SortByEnum SortBy { get; set; }
        /// <summary>
        /// The subaccount
        /// </summary>
        public string Subaccount { get; set; }
        /// <summary>
        /// The abnormal_session
        /// </summary>
        public bool? AbnormalSession { get; set; }

        /// <summary>
        /// Generate the necessary parameters
        /// </summary>
        public override List<KeyValuePair<string, string>> GetParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            if (From != null)
            {
                p.Add(new KeyValuePair<string, string>("From", From));
            }

            if (To != null)
            {
                p.Add(new KeyValuePair<string, string>("To", To));
            }

            if (FromCarrier != null)
            {
                p.Add(new KeyValuePair<string, string>("FromCarrier", FromCarrier));
            }

            if (ToCarrier != null)
            {
                p.Add(new KeyValuePair<string, string>("ToCarrier", ToCarrier));
            }

            if (FromCountryCode != null)
            {
                p.Add(new KeyValuePair<string, string>("FromCountryCode", FromCountryCode));
            }

            if (ToCountryCode != null)
            {
                p.Add(new KeyValuePair<string, string>("ToCountryCode", ToCountryCode));
            }

            if (Branded != null)
            {
                p.Add(new KeyValuePair<string, string>("Branded", Branded.Value.ToString().ToLower()));
            }

            if (VerifiedCaller != null)
            {
                p.Add(new KeyValuePair<string, string>("VerifiedCaller", VerifiedCaller.Value.ToString().ToLower()));
            }

            if (HasTag != null)
            {
                p.Add(new KeyValuePair<string, string>("HasTag", HasTag.Value.ToString().ToLower()));
            }

            if (StartTime != null)
            {
                p.Add(new KeyValuePair<string, string>("StartTime", StartTime));
            }

            if (EndTime != null)
            {
                p.Add(new KeyValuePair<string, string>("EndTime", EndTime));
            }

            if (CallType != null)
            {
                p.Add(new KeyValuePair<string, string>("CallType", CallType));
            }

            if (CallState != null)
            {
                p.Add(new KeyValuePair<string, string>("CallState", CallState));
            }

            if (Direction != null)
            {
                p.Add(new KeyValuePair<string, string>("Direction", Direction));
            }

            if (ProcessingState != null)
            {
                p.Add(new KeyValuePair<string, string>("ProcessingState", ProcessingState.ToString()));
            }

            if (SortBy != null)
            {
                p.Add(new KeyValuePair<string, string>("SortBy", SortBy.ToString()));
            }

            if (Subaccount != null)
            {
                p.Add(new KeyValuePair<string, string>("Subaccount", Subaccount.ToString()));
            }

            if (AbnormalSession != null)
            {
                p.Add(new KeyValuePair<string, string>("AbnormalSession", AbnormalSession.Value.ToString().ToLower()));
            }

            if (PageSize != null)
            {
                p.Add(new KeyValuePair<string, string>("PageSize", PageSize.ToString()));
            }

            return p;
        }
    }

}